# Generated by Django 5.0.2 on 2024-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Тэг")),
                (
                    "title_tag",
                    models.ManyToManyField(related_name="tags", to="articles.article"),
                ),
            ],
        ),
    ]
