# Generated by Django 5.0.2 on 2024-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_tag_scope_delete_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="articles",
            field=models.ManyToManyField(
                related_name="tags", through="articles.Scope", to="articles.article"
            ),
        ),
    ]
