# Generated by Django 5.0.2 on 2024-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
