# Generated by Django 5.0.2 on 2024-02-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("image", models.CharField()),
                ("release_date", models.DateField()),
                (
                    "lte_exists",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
                ("slug", models.SlugField()),
            ],
        ),
    ]
